### ISSUE TITLE
Does this control only work on contact?

### ISSUE THREAD

**Issue by easybeat** [sudhakarverma610/MutliSelectNtoNSubgrid#2]
Hi

sorry but I don't understand your description. Does this control only work on contact to account N:N?

Or should it work on any entity N:N connection?

Please clarify this for me as I can't get it to work for a custom entity N:N relation.

Kind regards
Beat

**Comment by jackmicrosoft** [comment]
Same! It's not working for me either :(

**Comment by sudhakarverma610** [comment]
Issue got Fixed

**Comment by sudhakarverma610** [comment]
this contact can work for any n to n relationship

**Comment by sudhakarverma610** [comment]
so we can close this ticket thanks
