### ISSUE TITLE
Field Values

### ISSUE THREAD

**Issue by hdvan80** [sudhakarverma610/MutliSelectNtoNSubgrid#5]
hi, I'm beginner at this,

What should be the field values used for the control.

entityName_Display_key
defaultViewID_Display_key
defaultSelectedRecords_Display

Can someone give an example so I can understand this better?

thanks

**Comment by sudhakarverma610** [comment]
i dont think these are input 
we have following input only
   <property name="controlLabel" display-name-key="controlLabel_Key" description-key="controlLabel_Desc" of-type="SingleLine.Text" usage="input" required="true"/>
    <property name="controlImageURl" display-name-key="controlImageURl_Key" description-key="controlImageURl_Desc" of-type="SingleLine.Text" usage="input" required="true"/>

**Comment by hdvan80** [comment]
for controlLabel_key and controlImageURI_Key what parameters I need to set?

<img width="211" alt="Form_Opportunity" src="https://github.com/sudhakarverma610/MutliSelectNtoNSubgrid/assets/160675853/85623ef4-39f4-460e-be30-24acefde2936">


Let's say I want to load from the Users table.

thanks

**Comment by hdvan80** [comment]
hi sudhakarverma610,

I was able to get it to work in Sandbox, but when I try to import it into production environment I'm not able to find the control options. I tried to export and import the solution as managed app but still cannot see it. Would you know what the issue is or do I need to enable something to be able to import it to production? thanks

**Comment by sudhakarverma610** [comment]
now i have updated pcf you can delete and recreated pcf and import to your org after that you can export that solution as managed solution then import to other branch as managed
