### ISSUE TITLE
PCF Control not working

### ISSUE THREAD

**Issue by DameshPeri** [sudhakarverma610/MutliSelectNtoNSubgrid#7]
Hi,

So I have imported the managed solution, and am able to see the pcf control in my component list.

I have a subgrid which is many to many, and when I add the component to it, it doesn't work.

controlLabel_key : Annual Dinner and Dance (name of subgrid)
 controlImageURI_Key : dxp_resource (name of the image i have add)

All that happens is the subgrid disappears and a label 'Annual Dinner Dance' appears. 

Can you please let me know what I'm doing wrong.

Thanks

**Comment by DameshPeri** [comment]
![image](https://github.com/sudhakarverma610/MutliSelectNtoNSubgrid/assets/87134310/dd481b6c-d6ab-4ae1-b0ab-5a7730051a7a)

**Comment by sudhakarverma610** [comment]
Control has been updated plz use lasted version
