### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Ballzer0** [sudhakarverma610/MutliSelectNtoNSubgrid#9]
there is no licence under this repository. 

Looks like a really cool component, but im afraid to use it in case you come running after me with a pitchfork!

**Comment by Ballzer0** [comment]
> there is no licence under this repository.
> 
> Looks like a really cool component, but im afraid to use it in case you come running after me with a pitchfork!

or worse, lawyers

**Comment by sudhakarverma610** [comment]
Added sir thanks you so much

**Comment by Ballzer0** [comment]
thanks for adding it, ima fork and test it out. This has already saved me a lot of time!
